version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: <TASK_DEFINITION>
        LoadBalancerInfo:
          ContainerName: "development-task"
          ContainerPort: 80
        NetworkConfiguration:
          AwsvpcConfiguration:
            Subnets: ["subnet-0534d89e2b83a201c","subnet-0e5a94e7257bb59b9"]
            SecurityGroups: ["sg-09ac9e0eb9c7d29f1"]
            AssignPublicIp: "DISABLED"
version: 0.0
